USE master
GO

CREATE DATABASE HorasExtSup
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HORAS_EXT_SUP', FILENAME = N'D:\Bases de Datos\Data\HORAS_EXT_SUP.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HORAS_EXT_SUP_log', FILENAME = N'L:\Base de Datos\Log\HORAS_EXT_SUP_log.ldf' , SIZE = 6912KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE HorasExtSup SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC HorasExtSup.dbo.sp_fulltext_database @action = 'enable'
end
GO

ALTER DATABASE HorasExtSup SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE HorasExtSup SET ANSI_NULLS OFF 
GO

ALTER DATABASE HorasExtSup SET ANSI_PADDING OFF 
GO

ALTER DATABASE HorasExtSup SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE HorasExtSup SET ARITHABORT OFF 
GO

ALTER DATABASE HorasExtSup SET AUTO_CLOSE OFF 
GO

ALTER DATABASE HorasExtSup SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE HorasExtSup SET AUTO_SHRINK OFF 
GO

ALTER DATABASE HorasExtSup SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE HorasExtSup SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE HorasExtSup SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE HorasExtSup SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE HorasExtSup SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE HorasExtSup SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE HorasExtSup SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE HorasExtSup SET  DISABLE_BROKER 
GO

ALTER DATABASE HorasExtSup SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE HorasExtSup SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE HorasExtSup SET TRUSTWORTHY OFF 
GO

ALTER DATABASE HorasExtSup SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE HorasExtSup SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE HorasExtSup SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE HorasExtSup SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE HorasExtSup SET RECOVERY FULL 
GO

ALTER DATABASE HorasExtSup SET  MULTI_USER 
GO

ALTER DATABASE HorasExtSup SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE HorasExtSup SET DB_CHAINING OFF 
GO

ALTER DATABASE HorasExtSup SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE HorasExtSup SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE HorasExtSup SET  READ_WRITE 
GO
